project:
  type: website

website:
  site-url: https://qiufei.site/web-tool
  search: true
  # è®¾ç½®ç½‘ç«™å›¾æ ‡
  favicon: profile.jpg
  # back-to-top-navigation: true
  # bread-crumbs: true
  # title: "é¦–é¡µ"
  navbar:
    left:
      - text: "é¦–é¡µ"
        href: https://qiufei.site
    right:
      # - slide.qmd
      # - invest.qmd
      # - life.qmd
      - text: å¸‚åœº
        href: https://qiufei.site/web-market
      - text: æ„Ÿå—
        href: https://qiufei.site/web-mind
      - text: è¯¾ä»¶
        href: https://qiufei.site/slide
      - text: è®²ä¹‰
        href: https://qiufei.site/book
      - text: å·¥å…·
        href: https://qiufei.site/web-tool
      # - icon: github
      #   href: https://github.com/
      - about.qmd
  page-footer:
    left: ğŸ”‹[![](https://posit.co/wp-content/themes/Posit/assets/images/posit-logo-2024.svg){fig-alt="Posit" width=65px}](https://posit.co)
    center: 
      - text: "é‚±é£ &copy; 2008-2024"
      - text: "æµ™ICPå¤‡ 2024072710å·-1"
        href: "https://beian.miit.gov.cn"
      - text: "æµ™å…¬ç½‘å®‰å¤‡ 33021202002511å·"
        href: "http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=33021202002511"
    right:
      - icon: envelope-at-fill
        href: mailto:hfutqiufei@163.com
      # - text: â†
format:
  html:
    theme:
     light: journal
     dark: cyborg
    css: styles.css

execute:
  freeze: auto